wallpaper {
    monitor = eDP-1
    path = ~/.local/share/hyprpaper/wallpapers/walls/stalenhag/a_group_of_tall_buildings_with_cartoon_characters_on_them.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1 
    path = ~/.local/share/hyprpaper/wallpapers/walls/stalenhag/a_snow_covered_road_with_two_large_machines.jpg
    fit_mode = cover
}
